version: '3.8'

services:
  genieus:
    build:
      context: .
      dockerfile: Dockerfile
    image: genieus:1.0.0
    container_name: genieus
    ports:
      - "7474:7474"
      - "7687:7687"
      - "8000:8000"
      - "7000:7000"